[project]
name = "ball-beam-pid"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyfirmata>=1.1.0",
    "streamlit>=1.45.1",
]
